services:
  nginx:
    build:
      context: ./requirements/nginx
    env_file:
      - .env
    container_name: ${USER}_nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/ssl:/etc/nginx/ssl
    networks:
      - inception_network
    restart: unless-stopped
    depends_on:
      wordpress:
        condition: service_healthy

  wordpress:
    build:
      context: ./requirements/wordpress
    env_file:
      - .env
    container_name: ${USER}_wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception_network
    restart: unless-stopped
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      WORDPRESS_DB_HOST: "mariadb:3306"
      WORDPRESS_DB_USER: "${MYSQL_USER}"
      WORDPRESS_DB_PASSWORD: "${MYSQL_PASSWORD}"
      WORDPRESS_DB_NAME: "${MYSQL_DATABASE}"
      WORDPRESS_TABLE_PREFIX: wp_
    healthcheck:
      test: ["CMD", "wp", "core", "is-installed", "--allow-root"]
      interval: 10s
      timeout: 5s
      retries: 10

  mariadb:
    build:
      context: ./requirements/mariadb
    env_file:
      - .env
    container_name: ${USER}_mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception_network
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-uroot", "-p$${MYSQL_ROOT_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  inception_network:
    driver: bridge
    name: ${USER}_inception_network

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abouguri/data/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/abouguri/data/mariadb